hl.on("hyprland.start", function ()
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &")
  hl.exec_cmd("hyprpaper &")
  hl.exec_cmd("npx arrpc &")
  hl.exec_cmd("swaync &")
  hl.exec_cmd(portal .. " &")
  hl.exec_cmd(easyeffects .. " &")
  hl.exec_cmd("quickshell --path /data/development/quickshell --no-duplicate --daemonize &")  hl.exec_cmd("xrandr --output DP-1 --primary &")
  hl.exec_cmd("mullvad-vpn &")
  hl.exec_cmd("steam -silent &")
  hl.exec_cmd("systemctl --user start hyprpolkitagent &")
  hl.exec_cmd("vesktop &")
  hl.exec_cmd("spotify &")
  hl.exec_cmd(init_workspaces)
end)
